services:
  modbot:
    image: modbot
    env_file: .discordenv
  mongodb:
    image: mongo:latest
    env_file: .mongoenv
    command: [ mongod,  --noscripting]
    ports: 
      - 27017:27017
    volumes: 
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
