networks:
  app-tier:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
services:
  modmail:
    image: mod-bot
    env_file: .discordenv
    networks: 
      - app-tier
    command: tail -f /dev/null
  mongodb_container:
    image: mongo:latest
    env_file: .mongoenv
    command: [ mongod,  --noscripting]
      #    ports: 
      #     - 27017:27017
    volumes: 
      - mongodb_data_container:/data/db
    networks:
        app-tier:
            ipv4_address: 172.30.0.10

volumes:
  mongodb_data_container:
